"""empty message

Revision ID: 79b93a485595
Revises: ed988287af31
Create Date: 2017-11-26 03:57:38.949664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b93a485595'
down_revision = 'ed988287af31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registered', sa.Boolean(), nullable=True))
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'registered')
    # ### end Alembic commands ###
