version: '3'
services:
  app:
    build: ./app
    volumes:
      - /vagrant/app:/srv/www
      - /var/log:/var/log
      - /var/db:/var/db
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_DEBUG=1
      - LC_ALL=C.UTF-8 # Click + Python3 work-around
      - LANG=C.UTF-8
    env_file: app/app.env
    command: flask run -h 0.0.0.0 -p 8000
    ports:
      - "8000:8000"
  db:
    build: db/
    env_file: db/db.env
    volumes:
      - /var/lib/postgres/data/wmuc:/var/lib/postgres/data
    ports:
      - "5432:5432"
