version: '3'
services:
  app:
    build: ./app
    volumes:
      - /vagrant/app:/srv/www
      - /var/log:/var/log
      - /var/db:/var/db
  db:
    build: db/
    volumes:
      - /var/lib/postgres/data:/var/lib/postgres/data
  web:
    build: ./web
    volumes:
      - /vagrant:/srv/www
      - /var/log/nginx:/var/log/nginx
    ports:
      - "8000:8000"
    links:
      - app
