version: '3'
services:
  app:
    build: ./app
    volumes:
      - /vagrant/app:/srv/www
      - /var/log:/var/log
      - /var/db:/var/db
    command: ["uwsgi", "--ini", "/srv/uwsgi/uwsgi.ini", "--catch-exceptions"]
  db:
    build: db/
    env_file: db/db.env
    volumes:
      - /var/lib/postgres/data:/var/lib/postgres/data
    ports:
      - "5432:5432"
  web:
    build: ./web
    volumes:
      - /vagrant:/srv/www
      - /var/log/nginx:/var/log/nginx
    ports:
      - "8000:8000"
    links:
      - app
